from io import BytesIO


def _minimal_pdf(title: str) -> bytes:
    text = title.replace("(", "").replace(")", "")[:80]
    stream = f"BT /F1 18 Tf 72 720 Td ({text}) Tj ET"
    objects = [
        b"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
        b"2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
        b"3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
        b"4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
        f"5 0 obj << /Length {len(stream)} >> stream\n{stream}\nendstream endobj".encode(),
    ]
    pdf = BytesIO()
    pdf.write(b"%PDF-1.4\n")
    offsets = []
    for obj in objects:
        offsets.append(pdf.tell())
        pdf.write(obj + b"\n")
    xref = pdf.tell()
    pdf.write(f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n".encode())
    for offset in offsets:
        pdf.write(f"{offset:010d} 00000 n \n".encode())
    pdf.write(
        f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode()
    )
    return pdf.getvalue()


def generate_completion_certificate(engagement: dict, worker: dict, customer: dict) -> bytes:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import inch
        from reportlab.pdfgen import canvas
    except ImportError as exc:
        return _minimal_pdf(f"KaamNow Job Completion Certificate {engagement.get('id', '')}")

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    pdf.setFillColor(colors.HexColor("#FF6B35"))
    pdf.rect(0, height - 1.1 * inch, width, 1.1 * inch, fill=True, stroke=False)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(0.75 * inch, height - 0.65 * inch, "KaamNow")

    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(0.75 * inch, height - 1.75 * inch, "Job Completion Certificate")

    pdf.setFont("Helvetica", 12)
    y = height - 2.35 * inch
    rows = [
        ("Certificate ID", engagement.get("id", "")),
        ("Local Expert", worker.get("name") or engagement.get("worker_name", "")),
        ("Skill", ", ".join(worker.get("skills") or []) or engagement.get("worker_skill", "")),
        ("Trust Tier", str(worker.get("trust_tier", ""))),
        ("Job", engagement.get("job_title", "")),
        ("Date", engagement.get("job_date") or engagement.get("created_at", "")),
        ("Location", engagement.get("village") or engagement.get("address", "")),
        (
            "Amount Paid",
            f"Rs {engagement.get('payment_amount') or engagement.get('daily_rate') or 0}",
        ),
        ("Customer", customer.get("name") or engagement.get("customer_name", "")),
        ("Completed At", engagement.get("completed_at", "")),
    ]
    for label, value in rows:
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(0.75 * inch, y, f"{label}:")
        pdf.setFont("Helvetica", 11)
        pdf.drawString(2.35 * inch, y, str(value or "-")[:90])
        y -= 0.35 * inch

    pdf.setFillColor(colors.HexColor("#4B5563"))
    pdf.setFont("Helvetica", 9)
    pdf.drawString(0.75 * inch, 0.75 * inch, "Generated by KaamNow for completed work.")
    pdf.showPage()
    pdf.save()
    return buffer.getvalue()
