from io import BytesIO


def generate_completion_certificate(engagement: dict, worker: dict, customer: dict) -> bytes:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import inch
        from reportlab.pdfgen import canvas
    except ImportError as exc:
        raise RuntimeError("reportlab is required to generate certificates") from exc

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    pdf.setFillColor(colors.HexColor("#FF6B35"))
    pdf.rect(0, height - 1.1 * inch, width, 1.1 * inch, fill=True, stroke=False)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(0.75 * inch, height - 0.65 * inch, "KaamNow")

    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(0.75 * inch, height - 1.75 * inch, "Job Completion Certificate")

    pdf.setFont("Helvetica", 12)
    y = height - 2.35 * inch
    rows = [
        ("Certificate ID", engagement.get("id", "")),
        ("Local Expert", worker.get("name") or engagement.get("worker_name", "")),
        ("Skill", ", ".join(worker.get("skills") or []) or engagement.get("worker_skill", "")),
        ("Trust Tier", str(worker.get("trust_tier", ""))),
        ("Job", engagement.get("job_title", "")),
        ("Date", engagement.get("job_date") or engagement.get("created_at", "")),
        ("Location", engagement.get("village") or engagement.get("address", "")),
        (
            "Amount Paid",
            f"Rs {engagement.get('payment_amount') or engagement.get('daily_rate') or 0}",
        ),
        ("Customer", customer.get("name") or engagement.get("customer_name", "")),
        ("Completed At", engagement.get("completed_at", "")),
    ]
    for label, value in rows:
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(0.75 * inch, y, f"{label}:")
        pdf.setFont("Helvetica", 11)
        pdf.drawString(2.35 * inch, y, str(value or "-")[:90])
        y -= 0.35 * inch

    pdf.setFillColor(colors.HexColor("#4B5563"))
    pdf.setFont("Helvetica", 9)
    pdf.drawString(0.75 * inch, 0.75 * inch, "Generated by KaamNow for completed work.")
    pdf.showPage()
    pdf.save()
    return buffer.getvalue()
